/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cotizacion;

import java.awt.event.KeyEvent;
import java.util.Calendar;

import Conexion.Conexion;
import Ventas.PanelVentas;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana Karen
 */
public class PanelCotizacion extends javax.swing.JPanel {

    Calendar cal = Calendar.getInstance();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    String varFechaReg = cal.get(cal.DATE) + "-" + (cal.get(cal.MONTH) + 1) + "-" + cal.get(cal.YEAR);
    String horaActual = cal.get(Calendar.HOUR) + " : " + cal.get(Calendar.MINUTE) + " : " + cal.get(Calendar.SECOND);

    public static Statement stm = null;
    public static String bd = Conexion.nombreBD;
    public static String login = Conexion.usuarioBD;//"root";
    public static String password = Conexion.contrasena;//"280592ssmaylo";
    public static String url = "jdbc:mysql://" + Conexion.nombreServidor + ":" + Conexion.puerto + "/" + Conexion.nombreBD;

    public static java.sql.Connection con;
    public static java.sql.PreparedStatement pps;
    public static ResultSet rs;

    public static int numeroC;

    public static Double importeFinal = 0.0;
    public static double subtotalVentas = 0.0, totalConDescuentoExtra = 0.0, descuentoVentas = 0.0;

    /**
     * Creates new form PanelCotizacion
     */
    public PanelCotizacion() {
        initComponents();
        labelObtenerFecha.setText(varFechaReg);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cajaBuscarCliente = new javax.swing.JTextField();
        botonBuscarCliente = new javax.swing.JButton();
        botonNuevoCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCliente = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        labelLogo2 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelAsunto = new javax.swing.JLabel();
        labelUbicacion = new javax.swing.JLabel();
        labelAnexo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        labelObtenerTelefono = new javax.swing.JLabel();
        labelObtenerCorreo = new javax.swing.JLabel();
        labelObtenerDomicilio = new javax.swing.JLabel();
        labelObtenerColonia = new javax.swing.JLabel();
        labelObtenerRFC = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        labelRFC = new javax.swing.JLabel();
        labelImagenTelefono = new javax.swing.JLabel();
        labelImagenCorreo = new javax.swing.JLabel();
        labelImagenMapa = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        cajaAsunto = new javax.swing.JTextField();
        cajaUbicacion = new javax.swing.JTextField();
        labelNota1 = new javax.swing.JLabel();
        labelSubTotal = new javax.swing.JLabel();
        labelIVA = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelATE = new javax.swing.JLabel();
        labelObtenerATTE = new javax.swing.JLabel();
        botonPDF = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        cajaDescuento = new javax.swing.JTextField();
        cajaTotal = new javax.swing.JTextField();
        cajaIVA = new javax.swing.JTextField();
        cajaSubtotal = new javax.swing.JTextField();
        labelObtenerNombreCliente = new javax.swing.JLabel();
        areaLeyenda = new java.awt.TextArea();
        labelCelular = new javax.swing.JLabel();
        labelObtenerCelular = new javax.swing.JLabel();
        labelObtenerFecha = new javax.swing.JLabel();
        botonPrecioExtra = new javax.swing.JButton();
        labelEst2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(62, 64, 149));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cajaBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaBuscarClienteKeyTyped(evt);
            }
        });

        botonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        botonBuscarCliente.setText("Buscar");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        botonNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgAgregar.png"))); // NOI18N
        botonNuevoCliente.setText("Nuevo");
        botonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoClienteActionPerformed(evt);
            }
        });

        jScrollPane3.setVerifyInputWhenFocusTarget(false);

        listaCliente.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        listaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaClienteMouseClicked(evt);
            }
        });
        listaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaClienteKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(listaCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cajaBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarCliente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonNuevoCliente)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarCliente))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(botonNuevoCliente)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/todo lonas.png"))); // NOI18N

        labelCliente.setText("Cliente:");

        labelAsunto.setText("Asunto:");

        labelUbicacion.setText("Ubicación:");

        labelAnexo.setText("Le anexo la cotización solicitada, esperando poder servirle.");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Descripción", "Precio Unitario", "Cantidad", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        labelObtenerTelefono.setText("01 437 95 4 0092");

        labelObtenerCorreo.setText("todolonas@hotmail.com");

        labelObtenerDomicilio.setText("Calle Fco. I Madero No. 90");

        labelObtenerColonia.setText("Colonia Centro");

        labelObtenerRFC.setText("CAA084090943A");

        labelTelefono.setText("Teléfono:");

        labelCorreo.setText("Correo:");

        labelDomicilio.setText("Domicilio:");

        labelRFC.setText("RFC:");

        labelImagenTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iPhone-front-white-icon.png"))); // NOI18N

        labelImagenCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Communication-gmail-icon.png"))); // NOI18N

        labelImagenMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Google-Maps-icon.png"))); // NOI18N

        labelFecha.setText("Fecha:");

        labelCiudad.setText("Tlaltenango de S. R, Zacatecas");

        cajaAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaAsuntoKeyTyped(evt);
            }
        });

        cajaUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaUbicacionKeyTyped(evt);
            }
        });

        labelNota1.setText("Nota: Se requiere de un 50% de anticipo para realizar su trabajo y 50% al entregarlo.");

        labelSubTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSubTotal.setText("SubTotal:");

        labelIVA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelIVA.setText("IVA:");

        labelDescuento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDescuento.setText("Descuento:");

        labelATE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelATE.setText("ATENTAMENTE");

        labelObtenerATTE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelObtenerATTE.setText("Arq. Omar Alejandro Castañeda Alvarez");

        botonPDF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pdf-icon3.png"))); // NOI18N
        botonPDF.setText("PDF");
        botonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPDFActionPerformed(evt);
            }
        });

        labelTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTotal.setText("Total:");

        cajaDescuento.setText("0");
        cajaDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaDescuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaDescuentoKeyTyped(evt);
            }
        });

        cajaTotal.setEditable(false);
        cajaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTotalActionPerformed(evt);
            }
        });

        cajaIVA.setEditable(false);
        cajaIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaIVAActionPerformed(evt);
            }
        });

        cajaSubtotal.setEditable(false);

        areaLeyenda.setEnabled(false);
        areaLeyenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areaLeyendaKeyTyped(evt);
            }
        });

        labelCelular.setText("Celular:");

        labelObtenerCelular.setText("01 437 95 4 0092");

        botonPrecioExtra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgAgregar.png"))); // NOI18N
        botonPrecioExtra.setText("Precio Extra");
        botonPrecioExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrecioExtraActionPerformed(evt);
            }
        });

        labelEst2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelEst2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelLogo2)
                        .addGap(308, 308, 308)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelImagenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelImagenCorreo))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCelular)
                            .addComponent(labelTelefono)
                            .addComponent(labelCorreo))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObtenerCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelObtenerTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelObtenerCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCliente)
                            .addComponent(labelAsunto))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObtenerNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(cajaAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addComponent(labelImagenMapa)
                        .addGap(16, 16, 16)
                        .addComponent(labelDomicilio)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObtenerDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelObtenerColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelUbicacion)
                        .addGap(1, 1, 1)
                        .addComponent(cajaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRFC)
                            .addComponent(labelFecha))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObtenerRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelObtenerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(labelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelAnexo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botonPrecioExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(labelATE))
                            .addComponent(labelObtenerATTE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNota1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(areaLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)
                                        .addComponent(labelEst2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDescuento)
                                    .addComponent(labelSubTotal)
                                    .addComponent(labelIVA)
                                    .addComponent(labelTotal))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cajaTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(cajaIVA, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(botonPDF)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelLogo2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelImagenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelImagenCorreo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelCelular)
                        .addGap(6, 6, 6)
                        .addComponent(labelTelefono)
                        .addGap(6, 6, 6)
                        .addComponent(labelCorreo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelObtenerCelular)
                        .addGap(6, 6, 6)
                        .addComponent(labelObtenerTelefono)
                        .addGap(6, 6, 6)
                        .addComponent(labelObtenerCorreo)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelObtenerNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(cajaAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addGap(10, 10, 10)
                                .addComponent(labelAsunto))
                            .addComponent(labelImagenMapa)
                            .addComponent(labelDomicilio)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelObtenerDomicilio)
                                .addGap(6, 6, 6)
                                .addComponent(labelObtenerColonia)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelRFC)
                        .addGap(6, 6, 6)
                        .addComponent(labelFecha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelObtenerRFC)
                        .addGap(6, 6, 6)
                        .addComponent(labelObtenerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUbicacion)
                            .addComponent(cajaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(labelCiudad)
                .addGap(2, 2, 2)
                .addComponent(labelAnexo)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNota1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cajaSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSubTotal)))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaLeyenda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cajaDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDescuento))
                            .addComponent(labelEst2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIVA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonPrecioExtra))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelATE)
                        .addGap(16, 16, 16)
                        .addComponent(labelObtenerATTE)))
                .addGap(18, 18, 18)
                .addComponent(botonPDF)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/todo lonas.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        // TODO add your handling code here:
        LogicaCotizacion.buscarCliente();
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void botonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoClienteActionPerformed
        // TODO add your handling code here:
        TodoLonas.Principal.cardLayout.show(TodoLonas.Principal.panelContenedor, "cliente");
        Clientes.PanelClientes.labelRegresarClientes.setVisible(true);
    }//GEN-LAST:event_botonNuevoClienteActionPerformed

    private void cajaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTotalActionPerformed

    private void cajaIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaIVAActionPerformed

    private void listaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaClienteMouseClicked
        String nombre = "";
        if (evt.getClickCount() == 2) {
            nombre = "" + listaCliente.getSelectedValue();
//            labelObtenerNombreCliente.setText("" + listaCliente.getSelectedValue());
            LogicaCotizacion.cliente.removeAllElements();
            listaCliente.setModel(LogicaCotizacion.cliente);
            cajaBuscarCliente.setText("");
            if (nombre.equals("null")) {
                System.out.println("se encontro cliente");
                botonPDF.setEnabled(false);
                botonNuevoCliente.setEnabled(true);
                botonPrecioExtra.setEnabled(false);
            } else {
                labelObtenerNombreCliente.setText(nombre);
                botonPDF.setEnabled(true);
                botonPrecioExtra.setEnabled(true);
                cajaDescuento.setEnabled(true);
                Cotizacion.LogicaCotizacion.obtenerDatosOperaciones();
                if (cajaDescuento.getText().isEmpty()) {
                    cajaDescuento.setText("0");
                }
            }
        }
    }//GEN-LAST:event_listaClienteMouseClicked

    private void listaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaClienteKeyPressed

    }//GEN-LAST:event_listaClienteKeyPressed

    private void botonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPDFActionPerformed
        // TODO add your handling code here:
        guardarCotizacion.guardarTablaCotiza();
        guardarCotizacion.guardarDetallesCotiza();
        ExportarPDF.guardarPDF();
        limpiarCotizacion();
    }//GEN-LAST:event_botonPDFActionPerformed

    private void cajaBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaBuscarClienteKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z')
                && (caracter != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
        if (cajaBuscarCliente.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaBuscarClienteKeyTyped

    private void cajaAsuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaAsuntoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (cajaBuscarCliente.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaAsuntoKeyTyped

    private void cajaUbicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaUbicacionKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if (cajaBuscarCliente.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaUbicacionKeyTyped

    private void areaLeyendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaLeyendaKeyTyped
        char caracter = evt.getKeyChar();

        if (areaLeyenda.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_areaLeyendaKeyTyped

    private void botonPrecioExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrecioExtraActionPerformed
        // TODO add your handling code here:
        new DatosExtra().setVisible(true);
    }//GEN-LAST:event_botonPrecioExtraActionPerformed

    private void cajaDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDescuentoKeyReleased
        // TODO add your handling code here:
        double descuento = 0, subtotal, resultado1, resultado2;
        importeFinal = 0.0;
        
        if (!cajaDescuento.getText().isEmpty()) {
            if (Double.parseDouble(cajaDescuento.getText())>50) {
                descuento=0;
                cajaDescuento.setText("0");
            }   
            else
            {
                descuento = Double.parseDouble(cajaDescuento.getText()) / 100;
                subtotal = Double.parseDouble(cajaSubtotal.getText());
                double iva = Double.parseDouble(LogicaCotizacion.iva) / 100;
                resultado2 = subtotal * iva;
                cajaIVA.setText("" + Math.rint(resultado2 * 100) / 100);

                totalConDescuentoExtra = (subtotal - (subtotal * descuento)) + resultado2;
                cajaTotal.setText("" + Math.rint(totalConDescuentoExtra * 100) / 100);
                importeFinal = totalConDescuentoExtra;
            }
        } else {
//            cajaTotal.setText("");
        }
    }//GEN-LAST:event_cajaDescuentoKeyReleased

    private void cajaDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDescuentoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != evt.VK_BACK_SPACE) && (caracter != '.')) {
            evt.consume();
        }
        if (cajaDescuento.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaDescuentoKeyTyped

    public static void limpiarCotizacion() {
        labelObtenerNombreCliente.setText("");
        cajaAsunto.setText("");
        cajaUbicacion.setText("");
        cajaSubtotal.setText("");
        cajaTotal.setText("");
        cajaDescuento.setText("");
        cajaIVA.setText("");

        DefaultTableModel temp = (DefaultTableModel) tablaProductos.getModel();
        while (temp.getRowCount() > 0) {
            temp.removeRow(0);
        }
        botonPrecioExtra.setEnabled(false);
        botonPDF.setEnabled(false);
        TodoLonas.Principal.cardLayout.show(TodoLonas.Principal.panelContenedor, "ventas");
        
        //Limpeiza de la parte relacionada con ventas
        DefaultTableModel temp2 = (DefaultTableModel) Ventas.PanelVentas.tablaPedidos.getModel();
        while (temp2.getRowCount() > 0) {
            temp2.removeRow(0);
        }
        Ventas.PanelVentas.cajaSubtotal.setText("");
        Ventas.PanelVentas.cajaDescuento.setText("");
        Ventas.PanelVentas.cajaTotal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static java.awt.TextArea areaLeyenda;
    private javax.swing.JButton botonBuscarCliente;
    public static javax.swing.JButton botonNuevoCliente;
    public static javax.swing.JButton botonPDF;
    public static javax.swing.JButton botonPrecioExtra;
    public static javax.swing.JTextField cajaAsunto;
    public static javax.swing.JTextField cajaBuscarCliente;
    public static javax.swing.JTextField cajaDescuento;
    public static javax.swing.JTextField cajaIVA;
    public static javax.swing.JTextField cajaSubtotal;
    public static javax.swing.JTextField cajaTotal;
    public static javax.swing.JTextField cajaUbicacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel labelATE;
    public static javax.swing.JLabel labelAnexo;
    public static javax.swing.JLabel labelAsunto;
    public static javax.swing.JLabel labelCelular;
    public static javax.swing.JLabel labelCiudad;
    public static javax.swing.JLabel labelCliente;
    public static javax.swing.JLabel labelCorreo;
    public static javax.swing.JLabel labelDescuento;
    public static javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEst2;
    public static javax.swing.JLabel labelFecha;
    public static javax.swing.JLabel labelIVA;
    private javax.swing.JLabel labelImagenCorreo;
    private javax.swing.JLabel labelImagenMapa;
    public static javax.swing.JLabel labelImagenTelefono;
    private javax.swing.JLabel labelLogo2;
    public static javax.swing.JLabel labelNota1;
    public static javax.swing.JLabel labelObtenerATTE;
    public static javax.swing.JLabel labelObtenerCelular;
    public static javax.swing.JLabel labelObtenerColonia;
    public static javax.swing.JLabel labelObtenerCorreo;
    public static javax.swing.JLabel labelObtenerDomicilio;
    public static javax.swing.JLabel labelObtenerFecha;
    public static javax.swing.JLabel labelObtenerNombreCliente;
    public static javax.swing.JLabel labelObtenerRFC;
    public static javax.swing.JLabel labelObtenerTelefono;
    public static javax.swing.JLabel labelRFC;
    public static javax.swing.JLabel labelSubTotal;
    public static javax.swing.JLabel labelTelefono;
    public static javax.swing.JLabel labelTotal;
    public static javax.swing.JLabel labelUbicacion;
    public static javax.swing.JList listaCliente;
    public static javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
